USE [TwoFactorAuthentication]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[devices](
	[id] [uniqueidentifier] NOT NULL,
	[user_id] [uniqueidentifier] NOT NULL,
	[device_mac] [varchar](12) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[devices] ADD  DEFAULT (newid()) FOR [id]
GO

ALTER TABLE [dbo].[devices]  WITH CHECK ADD  CONSTRAINT [FK_devices_users] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[devices] CHECK CONSTRAINT [FK_devices_users]
GO

ALTER TABLE [dbo].[devices]  WITH CHECK ADD  CONSTRAINT [CHK_device_id] CHECK  (([id]<>'00000000-0000-0000-0000-000000000000'))
GO

ALTER TABLE [dbo].[devices] CHECK CONSTRAINT [CHK_did]
GO


